### ISSUE TITLE
NCP API 구성 파일에서 api-access와 api-secret의 역할에 대해 질문드립니다

### ISSUE THREAD

**Issue by huongttt3506** [simidot/ncpmaps#1]
안녕하세요,

저는 현재 공부 중인 학생입니다. 우연히 NCP API에 관한 귀하의 저장소를 찾았습니다. 그러나 구성 파일(yaml)에서 몇 가지 이해가 안 되는 부분이 있어 질문드립니다.

yaml 파일의 일부분은 다음과 같습니다:

```
ncp:
  api:
    client-id: 
    client-secret: 
    api-access:
    api-secret: 
 ```
저는 client-id와 client-secret은 NCP API에 등록할 때 제공받는 정보라는 것을 이해했습니다. 그러나 api-access와 api-secret이 무엇을 의미하는지 잘 모르겠습니다.

이 두 항목이 어떤 역할을 하고, 어디에서 얻을 수 있는지 설명해 주실 수 있을까요?

도움 주시면 감사하겠습니다!
